'use client'

import { useCallback, useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import type { ArrivalPlan, LiveSignal, ReadinessPrefs } from '@/lib/types'

/**
 * AIExplanationCard — drop-in card that asks the deterministic
 * /api/explain-arrival-plan cascade (Groq → Gemini → template) to explain
 * why the current gate was recommended, then renders the result with a
 * source badge, latency, and a regenerate control.
 *
 * The endpoint contract is unchanged. The component is the standard way
 * any surface (Hub, Conditions, Journey, Staff Console) can show the
 * "best-available" AI explanation while still inheriting the sanitizer
 * and gate-hallucination guardrails from the route handler.
 */

interface ExplainResponse {
  explanation: string
  source: 'template' | 'groq' | 'gemini'
  generatedAt: string
  latencyMs: number
  requestId: string
  llmDiscarded?: boolean
}

interface AIExplanationCardProps {
  plan: ArrivalPlan
  prefs: ReadinessPrefs | null
  signals: LiveSignal[]
  eventName: string
  venueName: string
  ticketSection: string
  /** Light = white card on light bg. Dark = slate-900 card on dark bg (Staff Console). */
  tone?: 'light' | 'dark'
  /** Optional override for the heading. Default: "Why this plan". */
  title?: string
  /** Optional subline under the heading. */
  subtitle?: string
}

const SOURCE_META: Record<
  ExplainResponse['source'],
  { label: string; color: string; tooltip: string }
> = {
  groq: {
    label: 'Groq',
    color: 'bg-violet-500/15 text-violet-300 border-violet-500/40',
    tooltip: 'Generated by Groq · sanitized · guarded',
  },
  gemini: {
    label: 'Gemini',
    color: 'bg-sky-500/15 text-sky-300 border-sky-500/40',
    tooltip: 'Generated by Gemini · sanitized · guarded',
  },
  template: {
    label: 'Template',
    color: 'bg-slate-500/15 text-slate-300 border-slate-500/40',
    tooltip:
      'Deterministic fallback template — used when no API keys are configured or both LLMs timed out',
  },
}

function buildRequest(
  plan: ArrivalPlan,
  prefs: ReadinessPrefs | null,
  signals: LiveSignal[],
  eventName: string,
  venueName: string,
  ticketSection: string,
) {
  // Pick the most recent staff signal at the recommended gate, if any.
  const recentStaff = signals
    .filter(
      (s) =>
        s.source === 'staff' &&
        s.gate_id === plan.recommended_gate.id &&
        Date.now() - new Date(s.created_at).getTime() < 60 * 60 * 1000,
    )
    .sort(
      (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime(),
    )[0]
  const fanSignalsAtGate = signals.filter(
    (s) =>
      s.source === 'fan' &&
      s.gate_id === plan.recommended_gate.id &&
      Date.now() - new Date(s.created_at).getTime() < 60 * 60 * 1000,
  )

  return {
    plan: {
      recommended_gate: {
        id: plan.recommended_gate.id,
        name: plan.recommended_gate.name,
        typical_wait_minutes: plan.recommended_gate.typical_wait_minutes,
        accessibility: plan.recommended_gate.accessibility,
        family_friendly: plan.recommended_gate.family_friendly,
        sections: plan.recommended_gate.sections,
      },
      leave_by_time: plan.leave_by_time,
      arrival_time: plan.arrival_time,
      route_summary: plan.route_summary,
      confidence: plan.confidence,
      confidence_reason: plan.confidence_reason,
      support_points: plan.support_points.slice(0, 6).map((sp) => ({
        id: sp.id,
        type: sp.type,
        name: sp.name,
      })),
    },
    user: {
      transport: prefs?.transport ?? null,
      group: prefs?.group ?? null,
      needs: prefs?.needs ?? [],
      section: ticketSection,
    },
    event: { name: eventName, venue: venueName },
    conditions: {
      recent_staff_sentiment: recentStaff?.sentiment ?? null,
      recent_fan_signal_count: fanSignalsAtGate.length,
    },
  }
}

export function AIExplanationCard({
  plan,
  prefs,
  signals,
  eventName,
  venueName,
  ticketSection,
  tone = 'light',
  title = 'Why this plan',
  subtitle,
}: AIExplanationCardProps) {
  const [data, setData] = useState<ExplainResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fetchExplanation = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const body = buildRequest(plan, prefs, signals, eventName, venueName, ticketSection)
      const res = await fetch('/api/explain-arrival-plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })
      if (!res.ok) {
        const errBody = await res.json().catch(() => ({}))
        throw new Error(errBody?.error?.message ?? `HTTP ${res.status}`)
      }
      const json: ExplainResponse = await res.json()
      setData(json)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to fetch explanation')
    } finally {
      setLoading(false)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    plan.recommended_gate.id,
    plan.confidence,
    plan.confidence_breakdown.percent,
    signals.length,
    prefs?.transport,
    prefs?.group,
  ])

  // Auto-fetch on mount + whenever the inputs that materially affect the
  // recommendation change. We don't refetch on every signal append — only
  // when the recommended gate id / confidence percent shifts.
  useEffect(() => {
    fetchExplanation()
  }, [fetchExplanation])

  const isDark = tone === 'dark'
  const containerClass = isDark
    ? 'rounded-2xl border border-slate-800 bg-slate-900 p-5'
    : 'rounded-2xl border border-violet-200 bg-gradient-to-br from-violet-50 via-white to-fuchsia-50/30 p-5'
  const titleClass = isDark
    ? 'font-bold text-white text-base leading-tight'
    : 'font-bold text-violet-900 text-base leading-tight'
  const kickerClass = isDark
    ? 'text-[10px] font-bold uppercase tracking-wider text-violet-300'
    : 'text-[10px] font-bold uppercase tracking-wider text-violet-700'
  const subClass = isDark ? 'text-[11px] text-slate-400' : 'text-[11px] text-slate-600'
  const bodyClass = isDark ? 'text-sm text-slate-200' : 'text-sm text-slate-700'
  const buttonClass = isDark
    ? 'inline-flex items-center gap-1 px-2.5 py-1 rounded-md bg-slate-800 hover:bg-slate-700 text-slate-200 text-[11px] font-bold'
    : 'inline-flex items-center gap-1 px-2.5 py-1 rounded-md bg-white border border-violet-200 hover:bg-violet-50 text-violet-700 text-[11px] font-bold'

  return (
    <div className={containerClass}>
      <div className="flex items-start justify-between gap-3 mb-3">
        <div className="min-w-0">
          <div className={kickerClass}>✨ {title}</div>
          {subtitle && <div className={`${subClass} mt-0.5`}>{subtitle}</div>}
        </div>
        <button
          onClick={fetchExplanation}
          disabled={loading}
          className={`${buttonClass} disabled:opacity-50 flex-shrink-0`}
          title="Re-run the AI cascade"
        >
          <span className={loading ? 'inline-block animate-spin' : ''}>↻</span>
          {loading ? 'Generating' : 'Regenerate'}
        </button>
      </div>

      {error && (
        <div
          className={`rounded-lg px-3 py-2 text-xs mb-2 ${
            isDark
              ? 'bg-rose-500/10 border border-rose-500/30 text-rose-300'
              : 'bg-rose-50 border border-rose-200 text-rose-700'
          }`}
        >
          ⚠ {error}. Falling back to template explanation below.
        </div>
      )}

      {loading && !data ? (
        <div className="space-y-2">
          <div className={`h-3 rounded ${isDark ? 'bg-slate-800' : 'bg-slate-100'} animate-pulse`} />
          <div
            className={`h-3 w-5/6 rounded ${
              isDark ? 'bg-slate-800' : 'bg-slate-100'
            } animate-pulse`}
          />
          <div
            className={`h-3 w-3/4 rounded ${
              isDark ? 'bg-slate-800' : 'bg-slate-100'
            } animate-pulse`}
          />
        </div>
      ) : (
        data && (
          <motion.div
            key={data.requestId}
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.35 }}
          >
            <p className={`${bodyClass} leading-relaxed whitespace-pre-line`}>
              {data.explanation}
            </p>

            <div className="mt-3 flex items-center gap-1.5 flex-wrap">
              <span
                title={SOURCE_META[data.source].tooltip}
                className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider border ${SOURCE_META[data.source].color}`}
              >
                ✨ Source: {SOURCE_META[data.source].label}
              </span>
              <span
                className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider border ${
                  isDark
                    ? 'bg-slate-800 border-slate-700 text-slate-300'
                    : 'bg-white border-slate-200 text-slate-600'
                }`}
              >
                ⏱ {data.latencyMs}ms
              </span>
              {data.llmDiscarded && (
                <span
                  title="LLM output mentioned a different gate — discarded by the mentionsWrongGate guardrail. Template kept."
                  className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider border ${
                    isDark
                      ? 'bg-amber-500/15 border-amber-500/40 text-amber-300'
                      : 'bg-amber-50 border-amber-200 text-amber-700'
                  }`}
                >
                  ⚠ Guardrail kicked in
                </span>
              )}
              <span
                className={`text-[10px] ${isDark ? 'text-slate-500' : 'text-slate-400'}`}
              >
                {new Date(data.generatedAt).toLocaleTimeString()}
              </span>
            </div>

            <p
              className={`text-[10px] ${
                isDark ? 'text-slate-500' : 'text-slate-400'
              } mt-2 leading-relaxed`}
            >
              Cascade: Groq → Gemini → Template. Sanitized for safety wording. Gate
              mentions are guarded against hallucination.
            </p>
          </motion.div>
        )
      )}
    </div>
  )
}
